[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]

const_format = "^0.2"
rand = "^0.8"
futures = "^0.3"
futures-util = "0.3.15"
futures-timer = "^3"

serde = "1"
serde_derive = "1"
serde_json = "1"
serde_repr = "0.1.5"

