unstable_features = true

comment_width = 140
max_width = 120

format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
newline_style = "Unix"
normalize_comments = true
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true
